### ISSUE TITLE
GLIBCXX version is too new

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/tinyfk#51]
on older system (ubuntu16.04):
``` 
root@a8e8891acba9:/# python
Python 2.7.12 (default, Mar  1 2021, 11:38:31) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinyfk 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tinyfk/__init__.py", line 4, in <module>
    from . import _tinyfk
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python2.7/dist-packages/tinyfk/_tinyfk.so)
```

**Comment by HiroIshida** [comment]
Fixed in https://github.com/HiroIshida/tinyfk/pull/52
